// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            3
// Async Callback (empty):               1
// Total number of exported functions:   5

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    contract
    (
        init => init
        send_back_from_sc_async_v1 => send_back_from_sc_async_v1
        send_back_from_sc_async_v2 => send_back_from_sc_async_v2
        send_back => send_back
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
